CREATE TABLE movies
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    year_oscar      VARCHAR(255),
    category        VARCHAR(255),
    nominee         TEXT,
    additional_info TEXT,
    won             BOOLEAN,
    CONSTRAINT pk_movies PRIMARY KEY (id)
);